### ISSUE TITLE
3.14.1 ends with out of context text

### ISSUE THREAD

**Issue by o0ragman0o** [chronaeon/beigepaper#1]
Firstly, thanks for this work! Such a comprehensive document has been long time missing resource. I'm greatly appreciative of the gaps it's filling in my understanding.

To the issue, 3.14.1 on Ethash, the end paragraph includes out of context text relating to contract engineering with a perhaps unmarked-up subtitle 'Implementing Contracts'

    Implementing Contracts There are several patterns
    of contracts engineering that allow particular useful
    behaviours; two of these that I will briefly discuss are
    data feeds and random numbers

**Comment by chronaeon** [comment]
You're very welcome! Thanks for the feedback. This is now addressed in PR 6d31cf6, so I'll close this one.
