### ISSUE TITLE
Start with lower version number

### ISSUE THREAD

**Issue by holgerd77** [chronaeon/beigepaper#2]
Really nice and interesting initiative, enjoyed reading so far! 😄 📖 

The only criticism I have: maybe don't start with such a high version number ``v0.9.5`` but with something lower - e.g. ``v0.7.0`` and give this some time to evolve, with improvements from the community and generally some community building around it.

Then you can give this some more time to evolve towards a ``v1.0`` release, which will stand stand on broader shoulders, being reviewed more closely and will generally have a better stance and being more respected in the community.

**Comment by chronaeon** [comment]
Thanks for the input. I'll change it to 0.7.0 for now.  Let me know if you have any ideas on how to implement an objective progressive versioning system.
