### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pirapira** [chronaeon/beigepaper#3]
Yellow Paper is distributed under Creative Commons Attribution Share Alike 4.0, but Beige Paper is distributed under MIT License.  Why did the licensing conditions change?

**Comment by pirapira** [comment]
I found a [comment](https://www.reddit.com/r/ethereum/comments/7zzd6f/beige_paper_a_rewrite_of_the_yellow_paper_for/dut67sf/) saying that the Beige Paper is done from scratch.

**Comment by pirapira** [comment]
Poking @gavofyork

**Comment by chronaeon** [comment]
@pirapira The Beigepaper is a derivative work that uses the Yellowpaper as a primary source. It also sources the Ethereum Wiki. The code base is entirely my own work, as you can easily see. I'm closing this for now. If you notice any explicit copyright violations feel free to re-open.
