### ISSUE TITLE
Audiobook

### ISSUE THREAD

**Issue by jamesray1** [chronaeon/beigepaper#4]
I don't have time to review your paper, but I suggest you consider also making an audiobook so that people can learn about the EVM while they do other things.

**Comment by chronaeon** [comment]
That's a great idea. I'm going to assign you to this issue, and let me know when you find someone to do the narration.

**Comment by jamesray1** [comment]
https://twitter.com/JamesCRay01/status/970505299470659584?s=19

**Comment by chronaeon** [comment]
@jamesray1 give this a try: https://play.google.com/store/apps/details?id=com.hyperionics.avar&hl=en

It's only available on Android AFAIK, but it's excellent for technical stuff, like the YP, that you can't find recorded audiobooks for.

**Comment by chronaeon** [comment]
I'll take your Hooray! + Re-Tweet as saying that this solution has worked for you. Now we just need to find a solution for other platforms. 

Audio recordings are one option, but full audio recordings might best be saved until a 1.0 version of the paper.  I talked to Hyperionics Tech (makes Voice Aloud) about building support for other platforms but they are putting all their effort into their screen capture software and don't intend to do that with Voice Aloud. Another option would be to acquire the rights to Voice Aloud through a buyout and make the code open source. I don't know how to valuate their software though and make them a fair offer however.

**Comment by chronaeon** [comment]
@jamesray1 I'll take your Hooray! + Re-Tweet as saying that this solution has worked for you. Are you still interested in creating Audiobook recordings, or can we close the issue now?

**Comment by jamesray1** [comment]
I tried to use the app this morning to read a page in the Rust book but it doesn't read and display code very well, but it's better than nothing.

**Comment by chronaeon** [comment]
@jamesray1 that's an unfortunate situation with the Rust book. I can't help you with that. I'm closing this for now. If you have an issue with it reading the Beigepaper, feel free to reopen.
