### ISSUE TITLE
Sp. Pg3 'Indrexed' should be 'Indexed'

### ISSUE THREAD

**Issue by BenderDrummer** [chronaeon/beigepaper#9]
Great job on the paper!

Small spelling mistake in the PDF beige paper, no biggie.

Pg 3
Paragraph 4
Sentence 2

'Indrexed' should possibly read 'Indexed'

Cheers

**Comment by BenderDrummer** [comment]
Another one here.. It's no big deal, I make these kinds of typos all the time.

Pg 7
Paragraph 2
Sentence 2

'effeffect' should be 'effect'

**Comment by chronaeon** [comment]
Thanks for this issue! These are fixed in 7d92caa93bdc35c3edbf329430beda6c2efbfb9b.
